# Generated by Django 5.1.1 on 2024-10-08 06:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_content_blog_body_remove_blog_author_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'body'], name='blog_gin_index', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
